// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-Rxg3R-NkIODPX3uoG3oc_NNOl3FlWE',
    appId: '1:534906906908:web:00110fa0b154a55ecb72d9',
    messagingSenderId: '534906906908',
    projectId: 'signup-df4fb',
    authDomain: 'signup-df4fb.firebaseapp.com',
    databaseURL: 'https://signup-df4fb-default-rtdb.firebaseio.com',
    storageBucket: 'signup-df4fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNY1qgRyr4s3V3FtHlwf_6024zDPJ-mQ',
    appId: '1:534906906908:android:429c3db0998b1844cb72d9',
    messagingSenderId: '534906906908',
    projectId: 'signup-df4fb',
    databaseURL: 'https://signup-df4fb-default-rtdb.firebaseio.com',
    storageBucket: 'signup-df4fb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-Rxg3R-NkIODPX3uoG3oc_NNOl3FlWE',
    appId: '1:534906906908:web:4949d2f4989b5fd1cb72d9',
    messagingSenderId: '534906906908',
    projectId: 'signup-df4fb',
    authDomain: 'signup-df4fb.firebaseapp.com',
    databaseURL: 'https://signup-df4fb-default-rtdb.firebaseio.com',
    storageBucket: 'signup-df4fb.firebasestorage.app',
  );
}
